services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=corider-user-admin
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: